/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "STM32F103x8.h"
#include "stm32f103x8_gpio_driver.h"
#include "lcd.h"
#include "keypad.h"
#include "stm32f103x8_EXTI_driver.h"
#include "stm32f103x8_USART_driver.h"
#include "stm32f103x8_SPI_driver.h"
#include "stm32f103x8_I2C_driver.h"
#include "I2C_Slave_EEPROM.h"


 uint8_t IRQ_Flag = 0;
 uint32_t Glob_u32xPSR = 6;
 uint32_t Glob_u32ControlReg =6;
typedef enum Cpu_AccessLevel
{
	PRIVILEGED,   // 0
	UNPRIVILEGED  // 1
}Cpu_AccessLevel_t;

void Switch_CPU_AccessLevel(Cpu_AccessLevel_t Level)
{
	switch(Level)
	{
	case PRIVILEGED: //set CPU To privileged Mode
		__asm( "mrs r3,CONTROL \n\t"
			   "lsr r3,r3,#0x01 \n\t"
			   "lsl r3,r3,#0x01 \n\t"
			   "msr CONTROL,r3");
		break;

	case UNPRIVILEGED: //set CPU To unprivileged Mode
		__asm( "mrs r3,CONTROL \n\t"
			   "orr r3,#0x01 \n\t"
			   "msr CONTROL,r3");
		break;
	}


}

void EXTI9_CALLBACK(void)
{
	//IRQ_Flag = 1;
//	__asm("nop\n \t nop\n \t nop\n \t nop\n \t nop\n \t nop");
//
//
//	__asm("MRS %[OUT],PSR\t\n"
//			:[OUT]"=r"(Glob_u32xPSR)	);
//
//	__asm("nop\n \t nop\n \t nop\n \t nop\n \t nop\n \t nop");
}

void myFunc() //0x080080B4
{
	__asm("nop\n \t nop\n \t nop\n \t nop\n \t nop\n \t nop");

}
int main(void)
{
	uint32_t funcAddress = 0x080080B4; //0x007400000000; //0000 80B4 8000000
	//int in1, in2, out  = 0;
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	//Set EXTI Configuration
	EXTI_PinConfig_t EXTIConfig;
	EXTIConfig.EXTI_PIN = EXTI9PB9;
	EXTIConfig.Trigger_Case = EXTI_Trigger_RISING;
	EXTIConfig.P_IRQ_CallBack = EXTI9_CALLBACK;
	EXTIConfig.IRQ_EN = EXTI_IRQ_Enable;
	//MCAL_EXTI_GPIO_Init(&EXTIConfig);
    MCAL_EXTI_GPIO_Init(&EXTIConfig);

//    Switch_CPU_AccessLevel(UNPRIVILEGED);
//    Switch_CPU_AccessLevel(PRIVILEGED);

    void (*pFunc)() = myFunc;
    pFunc();

    pFunc = (void (*)())funcAddress;// //since the last bit is odd the cpu throw exception "hard fault"
    pFunc();
	IRQ_Flag = 1;
	while (1)
	{
		if(IRQ_Flag)
		{
			IRQ_Flag = 0;
		}
		else { /* Misra */ }
	}


}
